# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7d34213dc1174238ae181d85548e85fdeb92960727636e69240b755978b39add0f049687709e283c633ac6e45146cd8a766ed5eb759ca599b1fa256e40878312

test:
  secret_key_base: 102e7baf053e3b5aa950ac00599b5b9796699ae63666c1d1511e61202b58cd00bdd9676c6a36c9759d6238d06d3fb137fae190290cded54894720006336049ae

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
